//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Tracking_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_ID { get; set; }
        public string task_description { get; set; }
        public Nullable<System.DateTime> task_start_date { get; set; }
        public Nullable<System.DateTime> task_end_date { get; set; }
        public string task_status { get; set; }
        public Nullable<int> student_id_fk { get; set; }
        public Nullable<int> project_id_fk { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
    }
}
