//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Tracking_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Team_ID { get; set; }
        public Nullable<int> team_leader_id { get; set; }
        public Nullable<double> Total_mark { get; set; }
        public string mentor_email_fk { get; set; }
        public string supervisor_email_fk { get; set; }
        public Nullable<int> project_id_fk { get; set; }
    
        public virtual Mentor Mentor { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
